### ISSUE TITLE
Can't load the module with Percona 5.6 under Debian 7.0

### ISSUE THREAD

**Issue by davromaniak** [xiezhenye/mysql-plugin-disable-myisam#6]
Hi.

I just tried to build and use the module under Debian 7.0, and the build goes well, but when loading the plugin, I get the following error : 

mysql> INSTALL PLUGIN DISABLE_MYISAM SONAME 'dm.so';
ERROR 1126 (HY000): Can't open shared library '/usr/lib/mysql/plugin/dm.so' (errno: 2 /usr/lib/mysql/plugin/dm.so: undefined symbol: _ZTI9ha_myisam)

Here are the steps I did : 
- I added the percona APT repo and installed the following packages : percona-server-source-5.6 percona-server-server-5.6 percona-server-client-5.6 cmake libaio-dev
- I installed the build-deps for percona-server-5.6 : apt-get build-dep percona-server-5.6
- I retrieved your project : git clone https://github.com/xiezhenye/mysql-plugin-disable-myisam.git
- Under /usr/src : 
-- I extracted the sources : tar zxvf percona-server-source-5.6.tar.gz
-- I went to the /usr/src/percona-server/percona-server-5.6.21-70.1 directory, and performed the build/install like you wrote on the README file.
-- The build went well, without any error.
-- I just manually copied dm.so into /usr/lib/mysql/plugins
- Then I connected to the percona SQL server with the user root and launched "INSTALL PLUGIN DISABLE_MYISAM SONAME 'dm.so';"
- And I get the error given earlier.

Some information : 
- Percona server version: 5.6.21-70.1 Percona Server (GPL), Release 70.1, Revision 698
- OS : Debian 7.0 AMD64

Maybe I missed something during the install process.

In case you need extra information, don't hesitate to ask, I'll try to help you.

Thanks.

**Comment by xiezhenye** [comment]
I've tried installing this plugin on percona 5.6.21-70.1 and not met any problem.

**Comment by xiezhenye** [comment]
I've tried installing this plugin on percona 5.6.21-70.1 and not met any problem.
Ubuntu 14.04, x86_64

**Comment by davromaniak** [comment]
Hi.

Sorry for the late answer, I'm busy on other subjects now.

Today, I will try building the module on a Ubuntu 14.04 with percona 5.6.21-70.1.

Maybe I missed some dependencies on Debian and installing it on Ubuntu will help me find them.

Thanks.

**Comment by davromaniak** [comment]
Hi again.

I just tried... and still the same issue (ERROR 1126 (HY000): Can't open shared library '/usr/lib/mysql/plugin/dm.so' (errno: 2 /usr/lib/mysql/plugin/dm.so: undefined symbol: _ZTI9ha_myisam).

I must have missed something or I may be too dumb.

I'm searching.

Sorry for taking some of your time.

Thanks.

**Comment by davromaniak** [comment]
Hi again.

It's finally good.

Apparently, Percona DEB packages aren't built in a neutral environment. So when I try to build a plugin against it, the environment isn't the same (even with the cmake flags).

It would only work when using packages from the official debian repositories.

So to succeed, I simply rebuilt all the percona-server suite, and it's not what I wanted but it works.

So we can close this ticket.

Thanks.
